---
- name: Common ansible playbook
  hosts: vagrant
  sudo: True
  vars:
    docroot: /var/www/



  # Looks for roles/{role}/tasks/main.yml for tasks, roles/{role}/handlers/main.yml  
  # for handlers, etcetera.
  roles:
    - common
    - git
    - apache
    - php
    - memcached
    - mysql